### ISSUE TITLE
lora存checkpoint的问题

### ISSUE THREAD

**Issue by toddlt** [xxw1995/chatglm3-finetune#13]
请问您有遇到过lora训chatglm3时存下来的checkpoint里是一个12G的pytorch_model.bin而不是几十M的adapter_model.bin的情况吗

**Comment by xxw1995** [comment]
听起来是保存了全量的参数，而不是lora参数，重新定义下save函数

**Comment by toddlt** [comment]
嗯嗯，明白啦，改了管用了
